import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import TopNavigation from "@component/components/TopNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased mx-4 lg:mx-auto mb-10 ">
        <TopNavigation />
        <main className="flex-auto min-w-0 max-w-7xl w-full flex flex-col mx-auto my-8 px-2 md:px-6">
          {children}
        </main>
      </body>
    </html>
  );
}
